#ifndef ERRORES_H_INCLUDED
#define ERRORES_H_INCLUDED

#define ERROR_RESERVAR_MEMORIA_SEXO -10
#define ERROR_RESERVAR_MEMORIA_DOMICILIO -20
#define ERROR_RESERVAR_MEMORIA_EMPLEADO -30
#define ERROR_RESERVAR_MEMORIA_ESTADO_CIVIL -40
#define ERROR_RESERVAR_MEMORIA_NIVEL_ESTUDIO -50

#endif // ERRORES_H_INCLUDED
